### ISSUE TITLE
Option to disable commands

### ISSUE THREAD

**Issue by matthewdias** [lamabiker/atom-ember-cli-helper#33]
We use a docker-compose setup in dev, so I don't need the commands/console. Would be nice to have a setting to disable them so I don't have to close them each time.

**Comment by mariusandra** [comment]
Feel free to code it and submit a PR! :)

On a related note, I'm no longer using Atom nor Ember, so if anyone is willing to take over maintenance of this plugin, please get in touch!

**Comment by matthewdias** [comment]
https://github.com/apprentus/atom-ember-cli-helper/pull/35

**Comment by lamabiker** [comment]
This issue was fixed with #35
