### ISSUE TITLE
Settings option for the new "offer to generate file" feature

### ISSUE THREAD

**Issue by caseywatts** [lamabiker/atom-ember-cli-helper#43]
This new feature sounds useful, but based on how I've been using the file-switching tool I'd like to turn it off:
https://github.com/lamabiker/atom-ember-cli-helper/commit/23c181a8091a13d97144b6dfbb540cb367b49323

It looks like adding options to atom plugins is pretty straightforward, it would probably be easy to do something like this?
https://github.com/lamabiker/atom-ember-cli-helper/pull/35/files
I would have it default to its previous behavior.

(sidenote - I found a minor typo:
https://github.com/lamabiker/atom-ember-cli-helper/commit/23c181a8091a13d97144b6dfbb540cb367b49323#diff-742193ccdd99b6a6a737d75141713b24R275 )

**Comment by lamabiker** [comment]
@caseywatts, the latest release (v0.17.0) should now have that option. Thanks for spotting the typo!

**Comment by caseywatts** [comment]
awesome, thanks!! :)
