### ISSUE TITLE
Disabling Auto-Generation breaks file-toggling

### ISSUE THREAD

**Issue by caseywatts** [lamabiker/atom-ember-cli-helper#45]
When I disable the new option "Enable generating from blueprint", then file toggling (like via `ctrl+alt+e`) stops working. When I re-enable the option, it works again.

I have an idea why - I'll make a PR to show it.

**Comment by lamabiker** [comment]
v0.17.1 should have fixed this. Thanks!

**Comment by caseywatts** [comment]
I just confirmed that it's working 🎉
